# Diemnsiones

In [1]:
import numpy as np

## Escalar


In [4]:
x = np.array(42)
print("Escalar:", x, "- shape:", x.shape, "dims:", x.ndim)

Escalar: 42 - shape: () dims: 0


## Vector

In [3]:
x = np.array([42, 3, 5, 3, 6, 7])
print("Vector:", x, "- shape:", x.shape, "dims:", x.ndim)

Vector: [42  3  5  3  6  7] - shape: (6,) dims: 1


## Matriz


In [6]:
x = np.array([
    [42, 3, 5, 3, 6, 7],
    [66, 54, 5, 343, 6, 7]
])
print("Matriz:", x, "- shape:", x.shape, "dims:", x.ndim)

Matriz: [[ 42   3   5   3   6   7]
 [ 66  54   5 343   6   7]] - shape: (2, 6) dims: 2


## Tensor

In [9]:
x = np.array([[[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10]],
              [[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10]],
              [[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10]]
              ])
print("Tensor:", x, "- shape:", x.shape, "dims:", x.ndim)

Tensor: [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] - shape: (3, 2, 5) dims: 3


# Reshape

In [12]:
x = np.array([[0, 1],
              [2, 3],
              [4, 5],
              [6, 7]])

print(x, x.shape)
x = x.reshape(8, 1)
print('\n')
print(x, x.shape)
x = x.reshape(2, 4)
print('')
print(x, x.shape)
print('')
x = np.array([[0, 1],
              [2, 3],
              [4, 5],
              [6, 7]])
xt = x.T
print("original:")
print(x)
print("transpose:")
print(xt)

[[0 1]
 [2 3]
 [4 5]
 [6 7]] (4, 2)


[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)

[[0 1 2 3]
 [4 5 6 7]] (2, 4)

original:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
transpose:
[[0 2 4 6]
 [1 3 5 7]]
